/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FountainPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// fountain-cm6.ts
var import_view = require("@codemirror/view");
var regexPatterns = {
  sceneHeading: /^(?:INT\.|EXT\.|EST\.|INT\/EXT\.|I\/E\.|I\/X\.).*|^\.[^.].*$/i,
  transition: /^(?:[A-Z\s]+TO:|FADE TO BLACK\.|FADE OUT\.|CUT TO BLACK\.|>.*[^<])$/i,
  centered: /^>\s*.*\s*<$/,
  character: /^[\s]*[A-Z0-9\s]+(?: \([^)]+\))?\s*(?:\^)?$/,
  parenthetical: /^\s*\([^)]+\)\s*$/
};
function buildDecorations(view) {
  const builder = [];
  const doc = view.state.doc;
  let i = 1;
  let lastLineWasCharacter = false;
  let lastLineWasParenthetical = false;
  let lastLineWasDialogue = false;
  let lastLineWasEmpty = true;
  while (i <= doc.lines) {
    const line = doc.line(i);
    const text = line.text;
    const trimmed = text.trim();
    let customType = "";
    if (trimmed === "") {
      const isWhitespaceOnly = text.length > 0;
      const inDialogueContext = lastLineWasCharacter || lastLineWasParenthetical || lastLineWasDialogue;
      if (isWhitespaceOnly && inDialogueContext) {
        builder.push(import_view.Decoration.line({ class: "fountain-dialogue" }).range(line.from));
      } else {
        lastLineWasEmpty = true;
        lastLineWasCharacter = false;
        lastLineWasParenthetical = false;
        lastLineWasDialogue = false;
      }
      i++;
      continue;
    }
    if (regexPatterns.sceneHeading.test(trimmed)) {
      customType = "scene-heading";
      lastLineWasCharacter = false;
      lastLineWasParenthetical = false;
      lastLineWasDialogue = false;
    } else if (regexPatterns.centered.test(trimmed)) {
      customType = "centered";
      lastLineWasCharacter = false;
      lastLineWasParenthetical = false;
      lastLineWasDialogue = false;
    } else if (regexPatterns.transition.test(trimmed)) {
      customType = "transition";
      lastLineWasCharacter = false;
      lastLineWasParenthetical = false;
      lastLineWasDialogue = false;
    } else if (lastLineWasEmpty && regexPatterns.character.test(text) && !regexPatterns.sceneHeading.test(trimmed) && !regexPatterns.transition.test(trimmed)) {
      customType = "character";
      lastLineWasCharacter = true;
      lastLineWasParenthetical = false;
      lastLineWasDialogue = false;
    } else if ((lastLineWasCharacter || lastLineWasParenthetical || lastLineWasDialogue) && regexPatterns.parenthetical.test(trimmed)) {
      customType = "parenthetical";
      lastLineWasCharacter = false;
      lastLineWasParenthetical = true;
      lastLineWasDialogue = false;
    } else if (lastLineWasCharacter || lastLineWasParenthetical || lastLineWasDialogue) {
      customType = "dialogue";
      lastLineWasCharacter = false;
      lastLineWasParenthetical = false;
      lastLineWasDialogue = true;
    } else {
      customType = "action";
      lastLineWasCharacter = false;
      lastLineWasParenthetical = false;
      lastLineWasDialogue = false;
    }
    lastLineWasEmpty = false;
    builder.push(import_view.Decoration.line({ class: `fountain-${customType}` }).range(line.from));
    i++;
  }
  return import_view.Decoration.set(builder, true);
}
var fountainViewPlugin = import_view.ViewPlugin.fromClass(
  class {
    constructor(view) {
      this.decorations = buildDecorations(view);
    }
    update(update) {
      if (update.docChanged || update.viewportChanged) {
        this.decorations = buildDecorations(update.view);
      }
    }
  },
  {
    decorations: (v) => v.decorations
  }
);
var fountainLivePreview = [
  fountainViewPlugin
];

// settings.ts
var import_obsidian = require("obsidian");
var defaultCss = `/* Scene Headings */
.markdown-source-view.mod-cm6 .cm-content > .cm-line.fountain-scene-heading {
    text-transform: uppercase !important;
    font-weight: bold !important;
}

/* Character */
.markdown-source-view.mod-cm6 .cm-content > .cm-line.fountain-character {
    text-align: left !important;
    margin-left: 22ch !important;
    text-transform: uppercase !important;
}

/* Dialogue */
.markdown-source-view.mod-cm6 .cm-content > .cm-line.fountain-dialogue {
    margin-left: 10ch !important;
    max-width: 40ch !important;
}

/* Parenthetical */
.markdown-source-view.mod-cm6 .cm-content > .cm-line.fountain-parenthetical {
    text-align: left !important;
    margin-left: 16ch !important;
    max-width: 25ch !important;
}

/* Transitions */
.markdown-source-view.mod-cm6 .cm-content > .cm-line.fountain-transition {
    text-align: right !important;
    text-transform: uppercase !important;
}

/* Centered */
.markdown-source-view.mod-cm6 .cm-content > .cm-line.fountain-centered {
    text-align: center !important;
}

/* Dual Dialogue Left \u2014 override normal margins, constrain to left half */
.markdown-source-view.mod-cm6 .cm-content > .cm-line.fountain-dual-left.fountain-character {
    margin-left: 5ch !important;
}
.markdown-source-view.mod-cm6 .cm-content > .cm-line.fountain-dual-left.fountain-dialogue {
    margin-left: 0 !important;
    max-width: none !important;
}
.markdown-source-view.mod-cm6 .cm-content > .cm-line.fountain-dual-left.fountain-parenthetical {
    margin-left: 2ch !important;
}

/* Dual Dialogue Right \u2014 override normal margins for right column */
.markdown-source-view.mod-cm6 .cm-content > .cm-line.fountain-dual-right.fountain-character {
    margin-left: 5ch !important;
    text-align: left !important;
}
.markdown-source-view.mod-cm6 .cm-content > .cm-line.fountain-dual-right.fountain-dialogue {
    margin-left: 0 !important;
    max-width: none !important;
}
.markdown-source-view.mod-cm6 .cm-content > .cm-line.fountain-dual-right.fountain-parenthetical {
    margin-left: 2ch !important;
}
`;
var DEFAULT_SETTINGS = {
  customCss: defaultCss
};
var FountainSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Fountain Live Preview Settings" });
    containerEl.createEl("div", { text: "You can directly edit the CSS used for Fountain element rendering in the Live Preview here. This provides maximum flexibility." });
    new import_obsidian.Setting(containerEl).setName("Reset CSS to Defaults").setDesc("If you messed up your CSS or want to load newly added CSS features (like Dual Dialogue), click this button.").addButton((button) => {
      button.setButtonText("Reset Defaults").setWarning().onClick(async () => {
        this.plugin.settings.customCss = defaultCss;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Raw CSS").setDesc("Edit this CSS to change how Fountain elements look in Live Preview. This CSS is injected exactly as written.").addTextArea(
      (text) => text.setPlaceholder("Enter raw CSS here...").setValue(this.plugin.settings.customCss).onChange(async (value) => {
        this.plugin.settings.customCss = value;
        await this.plugin.saveSettings();
      })
    );
    const textAreas = containerEl.querySelectorAll("textarea");
    textAreas.forEach((ta) => {
      ta.style.width = "100%";
      ta.style.height = "400px";
      ta.style.fontFamily = "monospace";
    });
  }
};

// fountain-preview.ts
var import_obsidian2 = require("obsidian");
var FOUNTAIN_PREVIEW_VIEW = "fountain-preview-view";
var regexPatterns2 = {
  sceneHeading: /^(?:INT\.|EXT\.|EST\.|INT\/EXT\.|I\/E\.|I\/X\.).*|^\.[^.].*$/i,
  transition: /^(?:[A-Z\s]+TO:|FADE TO BLACK\.|FADE OUT\.|CUT TO BLACK\.|>.*[^<])$/i,
  centered: /^>\s*.*\s*<$/,
  character: /^[\s]*[A-Z0-9\s]+(?: \([^)]+\))?\s*(?:\^)?$/,
  parenthetical: /^\s*\([^)]+\)\s*$/
};
function parseFountain(text) {
  const rawLines = text.split("\n");
  const result = [];
  let lastLineWasCharacter = false;
  let lastLineWasParenthetical = false;
  let lastLineWasDialogue = false;
  let lastLineWasEmpty = true;
  for (const rawLine of rawLines) {
    const trimmed = rawLine.trim();
    if (trimmed === "") {
      const isWhitespaceOnly = rawLine.length > 0;
      const inDialogueContext = lastLineWasCharacter || lastLineWasParenthetical || lastLineWasDialogue;
      if (isWhitespaceOnly && inDialogueContext) {
        result.push({ type: "dialogue-blank", text: "", rawText: rawLine });
      } else {
        result.push({ type: "empty", text: "", rawText: rawLine });
        lastLineWasEmpty = true;
        lastLineWasCharacter = false;
        lastLineWasParenthetical = false;
        lastLineWasDialogue = false;
      }
      continue;
    }
    let type = "action";
    if (regexPatterns2.sceneHeading.test(trimmed)) {
      type = "scene-heading";
      lastLineWasCharacter = false;
      lastLineWasParenthetical = false;
      lastLineWasDialogue = false;
    } else if (regexPatterns2.centered.test(trimmed)) {
      type = "centered";
      lastLineWasCharacter = false;
      lastLineWasParenthetical = false;
      lastLineWasDialogue = false;
    } else if (/^#{1,6}\s/.test(trimmed)) {
      const levelMatch = trimmed.match(/^(#+)/);
      const level = Math.min(levelMatch ? levelMatch[1].length : 1, 3);
      type = `section-heading-${level}`;
      lastLineWasCharacter = false;
      lastLineWasParenthetical = false;
      lastLineWasDialogue = false;
    } else if (regexPatterns2.transition.test(trimmed)) {
      type = "transition";
      lastLineWasCharacter = false;
      lastLineWasParenthetical = false;
      lastLineWasDialogue = false;
    } else if (lastLineWasEmpty && regexPatterns2.character.test(rawLine) && !regexPatterns2.sceneHeading.test(trimmed) && !regexPatterns2.transition.test(trimmed)) {
      type = "character";
      lastLineWasCharacter = true;
      lastLineWasParenthetical = false;
      lastLineWasDialogue = false;
    } else if (
      // Dual-dialogue marker: CHARACTER ^ immediately after a dialogue block (no blank line required)
      (lastLineWasCharacter || lastLineWasParenthetical || lastLineWasDialogue) && regexPatterns2.character.test(rawLine) && trimmed.endsWith("^") && !regexPatterns2.sceneHeading.test(trimmed) && !regexPatterns2.transition.test(trimmed)
    ) {
      type = "character";
      lastLineWasCharacter = true;
      lastLineWasParenthetical = false;
      lastLineWasDialogue = false;
    } else if ((lastLineWasCharacter || lastLineWasParenthetical || lastLineWasDialogue) && regexPatterns2.parenthetical.test(trimmed)) {
      type = "parenthetical";
      lastLineWasCharacter = false;
      lastLineWasParenthetical = true;
      lastLineWasDialogue = false;
    } else if (lastLineWasCharacter || lastLineWasParenthetical || lastLineWasDialogue) {
      type = "dialogue";
      lastLineWasCharacter = false;
      lastLineWasParenthetical = false;
      lastLineWasDialogue = true;
    } else {
      lastLineWasCharacter = false;
      lastLineWasParenthetical = false;
      lastLineWasDialogue = false;
    }
    lastLineWasEmpty = false;
    result.push({ type, text: trimmed, rawText: rawLine });
  }
  return result;
}
function fountainToHTML(lines) {
  const htmlParts = [];
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    if (line.type === "character") {
      const leftBlock = collectDialogueBlock(lines, i);
      const afterLeft = i + leftBlock.length;
      let cursor = afterLeft;
      while (cursor < lines.length && lines[cursor].type === "empty") {
        cursor++;
      }
      if (cursor < lines.length && lines[cursor].type === "character" && lines[cursor].text.endsWith("^")) {
        const rightBlock = collectDialogueBlock(lines, cursor);
        htmlParts.push('<div class="fountain-dual-dialogue">');
        htmlParts.push('<div class="fountain-dual-col">');
        for (const dl of leftBlock) {
          htmlParts.push(renderLine(dl));
        }
        htmlParts.push("</div>");
        htmlParts.push('<div class="fountain-dual-col">');
        for (const dl of rightBlock) {
          if (dl.type === "character") {
            htmlParts.push(renderLine({ ...dl, text: dl.text.replace(/\s*\^\s*$/, "") }));
          } else {
            htmlParts.push(renderLine(dl));
          }
        }
        htmlParts.push("</div>");
        htmlParts.push("</div>");
        i = cursor + rightBlock.length;
        continue;
      }
    }
    htmlParts.push(renderLine(line));
    i++;
  }
  return htmlParts.join("\n");
}
function collectDialogueBlock(lines, startIdx) {
  const block = [];
  if (startIdx >= lines.length || lines[startIdx].type !== "character")
    return block;
  block.push(lines[startIdx]);
  let j = startIdx + 1;
  while (j < lines.length && (lines[j].type === "dialogue" || lines[j].type === "parenthetical" || lines[j].type === "dialogue-blank")) {
    block.push(lines[j]);
    j++;
  }
  return block;
}
function renderLine(line) {
  if (line.type === "empty" || line.type === "dialogue-blank") {
    return '<div class="fountain-empty">&nbsp;</div>';
  }
  let displayText = escapeHtml(line.text);
  if (line.type === "centered") {
    displayText = escapeHtml(line.text.replace(/^>\s*/, "").replace(/\s*<$/, ""));
  } else if (line.type === "transition") {
    displayText = escapeHtml(line.text.replace(/^>\s*/, ""));
  } else if (line.type.startsWith("section-heading")) {
    displayText = escapeHtml(line.text.replace(/^#+\s*/, ""));
  }
  return `<div class="fountain-line fountain-${line.type}">${displayText}</div>`;
}
function escapeHtml(text) {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
var FountainPreviewView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.trackedFile = null;
    // Remember last file even when pane is focused
    this.scrollSyncCleanup = null;
    this.plugin = plugin;
  }
  getViewType() {
    return FOUNTAIN_PREVIEW_VIEW;
  }
  getDisplayText() {
    return "Fountain Preview";
  }
  getIcon() {
    return "film";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    const header = document.createElement("div");
    header.style.cssText = "display:flex; align-items:center; justify-content:space-between; padding:4px 8px; border-bottom:1px solid var(--background-modifier-border);";
    const title = document.createElement("span");
    title.textContent = "\u{1F3AC} Fountain Preview";
    title.style.cssText = "font-weight:600; font-size:0.9em; color:var(--text-muted);";
    header.appendChild(title);
    const btnStyle = "cursor:pointer; font-size:0.8em; padding:2px 8px; border-radius:4px; border:1px solid var(--background-modifier-border); background:var(--background-secondary); color:var(--text-normal); margin-left:4px;";
    const refreshBtn = document.createElement("button");
    refreshBtn.textContent = "\u21BB Refresh";
    refreshBtn.style.cssText = btnStyle;
    refreshBtn.addEventListener("click", () => this.forceRefresh());
    header.appendChild(refreshBtn);
    const pdfBtn = document.createElement("button");
    pdfBtn.textContent = "\u{1F4C4} Export PDF";
    pdfBtn.style.cssText = btnStyle;
    pdfBtn.addEventListener("click", () => this.exportPdf());
    header.appendChild(pdfBtn);
    container.appendChild(header);
    this.styleEl = document.createElement("style");
    container.appendChild(this.styleEl);
    this.contentEl_inner = document.createElement("div");
    this.contentEl_inner.className = "fountain-preview-content";
    container.appendChild(this.contentEl_inner);
    this.applyCustomCss();
    this.registerEvent(this.app.workspace.on("active-leaf-change", (leaf) => {
      if (!leaf)
        return;
      const view = leaf.view;
      if (view instanceof import_obsidian2.MarkdownView && view.file) {
        this.trackedFile = view.file;
        this.renderFile();
        this.attachScrollSync(view);
      }
    }));
    this.registerEvent(this.app.vault.on("modify", (file) => {
      if (this.trackedFile && file.path === this.trackedFile.path) {
        this.renderFile();
      }
    }));
    this.registerEvent(this.app.workspace.on("editor-change", (editor, info) => {
      const mdView = info;
      if (mdView.file && this.trackedFile && mdView.file.path === this.trackedFile.path) {
        const content = editor.getValue();
        this.renderContent(content);
      }
    }));
    this.findActiveFile();
    this.renderFile();
  }
  async onClose() {
    if (this.scrollSyncCleanup) {
      this.scrollSyncCleanup();
      this.scrollSyncCleanup = null;
    }
  }
  /**
   * Find the currently active markdown file (if any).
   */
  findActiveFile() {
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof import_obsidian2.MarkdownView && view.file) {
        this.trackedFile = view.file;
        this.attachScrollSync(view);
        return;
      }
    }
  }
  /**
   * Force refresh (manual button).
   */
  async forceRefresh() {
    this.findActiveFile();
    await this.renderFile();
  }
  /**
   * Read the tracked file from disk and render.
   */
  async renderFile() {
    if (!this.trackedFile) {
      this.contentEl_inner.innerHTML = '<div style="text-align:center; color:var(--text-muted); padding:2em;">Open a .fountain file, then click \u21BB Refresh.</div>';
      return;
    }
    const content = await this.app.vault.read(this.trackedFile);
    this.renderContent(content);
  }
  /**
   * Render raw Fountain text into the preview pane.
   */
  renderContent(content) {
    const parsedLines = parseFountain(content);
    const html = fountainToHTML(parsedLines);
    this.contentEl_inner.innerHTML = html;
    this.applyCustomCss();
  }
  exportPdf() {
    if (!this.trackedFile) {
      new import_obsidian2.Notice("No file loaded in preview.");
      return;
    }
    const bodyHtml = this.contentEl_inner.innerHTML;
    new FountainPrintModal(this.app, this.plugin.settings.customCss || "", bodyHtml).open();
  }
  attachScrollSync(view) {
    if (this.scrollSyncCleanup) {
      this.scrollSyncCleanup();
      this.scrollSyncCleanup = null;
    }
    const editorEl = view.containerEl.querySelector(".cm-scroller");
    if (!editorEl)
      return;
    const previewEl = this.contentEl_inner;
    const handler = () => {
      const fraction = editorEl.scrollTop / Math.max(1, editorEl.scrollHeight - editorEl.clientHeight);
      previewEl.scrollTop = fraction * (previewEl.scrollHeight - previewEl.clientHeight);
    };
    editorEl.addEventListener("scroll", handler, { passive: true });
    this.scrollSyncCleanup = () => editorEl.removeEventListener("scroll", handler);
  }
  applyCustomCss() {
    if (this.styleEl) {
      const previewCss = `
.fountain-preview-content {
    font-family: "Courier Prime", "Courier New", Courier, monospace;
    font-size: 12pt;
    line-height: 1.5;
    max-width: 8.5in;
    margin: 0 auto;
    padding: 1in 1in;
    background: var(--background-primary);
    color: var(--text-normal);
}

.fountain-line {
    margin: 0;
    padding: 0;
}

.fountain-empty {
    min-height: 1em;
}

/* Scene Heading */
.fountain-scene-heading {
    text-transform: uppercase;
    font-weight: bold;
    margin-top: 1.5em;
}

/* Character */
.fountain-character {
    margin-left: 22ch;
    text-transform: uppercase;
    margin-top: 1em;
}

/* Dialogue */
.fountain-dialogue {
    margin-left: 10ch;
    max-width: 35ch;
}

/* Parenthetical */
.fountain-parenthetical {
    margin-left: 16ch;
    max-width: 25ch;
}

/* Transition */
.fountain-transition {
    text-align: right;
    text-transform: uppercase;
    margin-top: 1em;
}

/* Centered */
.fountain-centered {
    text-align: center;
}

/* Action */
.fountain-action {
    margin-top: 0.5em;
}

/* Section Headings */
.fountain-section-heading-1 {
    text-align: center;
    font-size: 1.4em;
    font-weight: bold;
    text-transform: uppercase;
    margin: 3em 0 2em;
    padding: 0.5em 0;
    border-top: 1px solid var(--background-modifier-border);
    border-bottom: 1px solid var(--background-modifier-border);
    color: var(--text-accent);
}

.fountain-section-heading-2 {
    font-weight: bold;
    text-transform: uppercase;
    margin: 2em 0 0.5em;
    color: var(--text-muted);
}

.fountain-section-heading-3 {
    font-weight: bold;
    margin: 1.5em 0 0.5em;
    color: var(--text-muted);
}

/* ===== Dual Dialogue ===== */
.fountain-dual-dialogue {
    display: flex;
    gap: 2ch;
    margin-top: 1em;
    width: 100%;
}

.fountain-dual-col {
    flex: 1;
    min-width: 0;
}

/* Override margins inside dual columns */
.fountain-dual-col .fountain-character {
    margin-left: 5ch;
    margin-top: 0;
}

.fountain-dual-col .fountain-dialogue {
    margin-left: 0;
    max-width: none;
}

.fountain-dual-col .fountain-parenthetical {
    margin-left: 2ch;
    max-width: none;
}
`;
      this.styleEl.textContent = previewCss;
      if (this.plugin.settings.customCss) {
        this.styleEl.textContent += "\n" + this.plugin.settings.customCss;
      }
    }
  }
};
var FountainPrintModal = class extends import_obsidian2.Modal {
  constructor(app, customCss, bodyHtml) {
    super(app);
    this.paperSize = "letter";
    this.margins = "normal";
    this.showPageNumbers = false;
    this.customCss = customCss;
    this.bodyHtml = bodyHtml;
  }
  onOpen() {
    const { contentEl, modalEl } = this;
    contentEl.empty();
    modalEl.style.cssText = "width:90vw; max-width:90vw; height:85vh; max-height:85vh; display:flex; flex-direction:column;";
    contentEl.style.cssText = "flex:1; display:flex; flex-direction:column; overflow:hidden; padding:0;";
    const toolbar = contentEl.createDiv();
    toolbar.style.cssText = "display:flex; align-items:center; gap:12px; padding:10px 16px; border-bottom:1px solid var(--background-modifier-border); flex-shrink:0; flex-wrap:wrap; background:var(--background-secondary);";
    const selStyle = "padding:3px 6px; border-radius:4px; border:1px solid var(--background-modifier-border); background:var(--background-primary); color:var(--text-normal); font-size:0.85em;";
    const labelStyle = "font-size:0.85em; color:var(--text-muted); white-space:nowrap;";
    const paperLabel = toolbar.createSpan({ text: "Paper:" });
    paperLabel.style.cssText = labelStyle;
    const paperSel = toolbar.createEl("select");
    paperSel.style.cssText = selStyle;
    [["letter", 'Letter (8.5"\xD711")'], ["a4", "A4 (210\xD7297mm)"]].forEach(([v, t]) => {
      paperSel.createEl("option", { value: v, text: t });
    });
    paperSel.value = this.paperSize;
    paperSel.addEventListener("change", () => {
      this.paperSize = paperSel.value;
      this.updatePreview(previewInner, previewStyle);
    });
    const marginLabel = toolbar.createSpan({ text: "Margins:" });
    marginLabel.style.cssText = labelStyle;
    const marginSel = toolbar.createEl("select");
    marginSel.style.cssText = selStyle;
    [["normal", 'Normal (1")'], ["narrow", 'Narrow (\xBE")'], ["tight", 'Tight (\xBD")']].forEach(([v, t]) => {
      marginSel.createEl("option", { value: v, text: t });
    });
    marginSel.value = this.margins;
    marginSel.addEventListener("change", () => {
      this.margins = marginSel.value;
      this.updatePreview(previewInner, previewStyle);
    });
    const pageNumWrap = toolbar.createDiv();
    pageNumWrap.style.cssText = "display:flex; align-items:center; gap:5px;";
    const pageNumCb = document.createElement("input");
    pageNumCb.type = "checkbox";
    pageNumCb.checked = this.showPageNumbers;
    pageNumWrap.appendChild(pageNumCb);
    const pageNumLabel = pageNumWrap.createSpan({ text: "Page numbers" });
    pageNumLabel.style.cssText = labelStyle;
    pageNumCb.addEventListener("change", () => {
      this.showPageNumbers = pageNumCb.checked;
    });
    const printBtn = toolbar.createEl("button");
    printBtn.textContent = "\u{1F5A8}\uFE0F Print / Save as PDF";
    printBtn.style.cssText = "margin-left:auto; padding:6px 16px; cursor:pointer; background:var(--interactive-accent); color:var(--text-on-accent); border:none; border-radius:4px; font-weight:600; font-size:0.9em;";
    printBtn.addEventListener("click", () => this.doPrint());
    const previewWrapper = contentEl.createDiv();
    previewWrapper.style.cssText = "flex:1; overflow-y:auto; background:#666; padding:24px; display:flex; flex-direction:column; align-items:center;";
    const previewStyle = previewWrapper.createEl("style");
    const previewInner = previewWrapper.createDiv({ cls: "fountain-preview-content fountain-modal-paper" });
    previewInner.innerHTML = this.bodyHtml;
    this.updatePreview(previewInner, previewStyle);
  }
  getMarginValue() {
    return this.margins === "narrow" ? "0.75in" : this.margins === "tight" ? "0.5in" : "1in";
  }
  updatePreview(previewInner, previewStyle) {
    const margin = this.getMarginValue();
    const width = this.paperSize === "a4" ? "210mm" : "8.5in";
    previewInner.style.cssText = `
            background: white !important;
            color: black !important;
            width: ${width};
            max-width: 100%;
            padding: ${margin};
            font-family: "Courier Prime", "Courier New", Courier, monospace;
            font-size: 12pt;
            line-height: 1.5;
            box-shadow: 0 4px 20px rgba(0,0,0,0.5);
            min-height: 10in;
        `;
    previewStyle.textContent = `
.fountain-modal-paper .fountain-line { margin: 0; padding: 0; color: black; }
.fountain-modal-paper .fountain-empty { min-height: 1em; }
.fountain-modal-paper .fountain-scene-heading { text-transform: uppercase; font-weight: bold; margin-top: 1.5em; color: black; }
.fountain-modal-paper .fountain-character { margin-left: 22ch; text-transform: uppercase; margin-top: 1em; color: black; }
.fountain-modal-paper .fountain-dialogue { margin-left: 10ch; max-width: 35ch; color: black; }
.fountain-modal-paper .fountain-parenthetical { margin-left: 16ch; max-width: 25ch; color: black; }
.fountain-modal-paper .fountain-transition { text-align: right; text-transform: uppercase; margin-top: 1em; color: black; }
.fountain-modal-paper .fountain-centered { text-align: center; color: black; }
.fountain-modal-paper .fountain-action { margin-top: 0.5em; color: black; }
.fountain-modal-paper .fountain-section-heading-1 { text-align: center; font-size: 1.4em; font-weight: bold; text-transform: uppercase; margin: 3em 0 2em; border-top: 1px solid #ccc; border-bottom: 1px solid #ccc; padding: 0.5em 0; color: black; }
.fountain-modal-paper .fountain-section-heading-2 { font-weight: bold; text-transform: uppercase; margin: 2em 0 0.5em; color: black; }
.fountain-modal-paper .fountain-section-heading-3 { font-weight: bold; margin: 1.5em 0 0.5em; color: black; }
.fountain-modal-paper .fountain-dual-dialogue { display: flex; gap: 2ch; margin-top: 1em; width: 100%; }
.fountain-modal-paper .fountain-dual-col { flex: 1; min-width: 0; }
.fountain-modal-paper .fountain-dual-col .fountain-character { margin-left: 5ch; margin-top: 0; }
.fountain-modal-paper .fountain-dual-col .fountain-dialogue { margin-left: 0; max-width: none; }
.fountain-modal-paper .fountain-dual-col .fountain-parenthetical { margin-left: 2ch; max-width: none; }
${this.customCss}`;
  }
  doPrint() {
    const margin = this.getMarginValue();
    const size = this.paperSize === "a4" ? "A4" : "letter";
    const pageNumberCss = this.showPageNumbers ? `@page { @bottom-right { content: counter(page); font-family: "Courier Prime", "Courier New", Courier, monospace; font-size: 10pt; } }` : "";
    const printCss = `
@page { size: ${size}; margin: ${margin}; }
${pageNumberCss}
* { box-sizing: border-box; }
body { margin: 0; padding: 0; background: white; color: black; }

.fountain-preview-content {
    font-family: "Courier Prime", "Courier New", Courier, monospace;
    font-size: 12pt; line-height: 1.5;
    max-width: 100%; margin: 0; padding: 0;
    background: white; color: black;
}
.fountain-line { margin: 0; padding: 0; }
.fountain-empty { min-height: 1em; }

.fountain-scene-heading {
    text-transform: uppercase; font-weight: bold;
    margin-top: 1.5em; page-break-after: avoid;
}
.fountain-character {
    margin-left: 22ch; text-transform: uppercase;
    margin-top: 1em; page-break-after: avoid;
}
/* No page-break-before:avoid on dialogue \u2014 lets long blocks flow naturally across pages */
.fountain-dialogue { margin-left: 10ch; max-width: 35ch; }
.fountain-parenthetical { margin-left: 16ch; max-width: 25ch; page-break-after: avoid; }
.fountain-transition { text-align: right; text-transform: uppercase; margin-top: 1em; }
.fountain-centered { text-align: center; }
.fountain-action { margin-top: 0.5em; }

.fountain-section-heading-1 {
    page-break-before: always; page-break-after: always;
    text-align: center; font-size: 1.4em; font-weight: bold;
    text-transform: uppercase; padding-top: 4in;
}
.fountain-section-heading-2 { font-weight: bold; text-transform: uppercase; margin-top: 2em; page-break-after: avoid; }
.fountain-section-heading-3 { font-weight: bold; margin-top: 1.5em; page-break-after: avoid; }

/* No page-break-inside:avoid on dual-dialogue \u2014 lets long dual blocks flow naturally */
.fountain-dual-dialogue { display: flex; gap: 2ch; margin-top: 1em; width: 100%; }
.fountain-dual-col { flex: 1; min-width: 0; }
.fountain-dual-col .fountain-character { margin-left: 5ch; margin-top: 0; }
.fountain-dual-col .fountain-dialogue { margin-left: 0; max-width: none; }
.fountain-dual-col .fountain-parenthetical { margin-left: 2ch; max-width: none; }

${this.customCss}`;
    const overlay = document.createElement("div");
    overlay.id = "fountain-print-overlay";
    overlay.className = "fountain-preview-content";
    overlay.innerHTML = this.bodyHtml;
    document.body.appendChild(overlay);
    const printStyle = document.createElement("style");
    printStyle.id = "fountain-print-style";
    printStyle.textContent = `
@media screen { #fountain-print-overlay { display: none !important; } }
@media print {
    body > *:not(#fountain-print-overlay) { display: none !important; }
    #fountain-print-overlay { display: block !important; }
}
${printCss}`;
    document.head.appendChild(printStyle);
    setTimeout(() => {
      window.print();
      setTimeout(() => {
        overlay.remove();
        printStyle.remove();
      }, 2e3);
    }, 200);
  }
  onClose() {
    this.contentEl.empty();
  }
};

// main.ts
var FountainPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    console.log("[Fountain Plugin] Loading");
    await this.loadSettings();
    this.registerExtensions(["fountain"], "markdown");
    this.registerEditorExtension(fountainLivePreview);
    this.registerView(
      FOUNTAIN_PREVIEW_VIEW,
      (leaf) => new FountainPreviewView(leaf, this)
    );
    this.addCommand({
      id: "open-fountain-preview",
      name: "Open Fountain Preview",
      callback: () => this.activatePreview()
    });
    this.addRibbonIcon("film", "Open Fountain Preview", () => {
      this.activatePreview();
    });
    this.addSettingTab(new FountainSettingTab(this.app, this));
    this.styleTag = document.createElement("style");
    this.styleTag.id = "fountain-custom-css";
    document.head.appendChild(this.styleTag);
    this.applyCssSettings();
    console.log("[Fountain Plugin] Loaded");
  }
  onunload() {
    console.log("[Fountain Plugin] Unloading");
    if (this.styleTag) {
      this.styleTag.remove();
    }
  }
  async activatePreview() {
    const existing = this.app.workspace.getLeavesOfType(FOUNTAIN_PREVIEW_VIEW);
    if (existing.length) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false);
    if (leaf) {
      await leaf.setViewState({
        type: FOUNTAIN_PREVIEW_VIEW,
        active: true
      });
      this.app.workspace.revealLeaf(leaf);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.applyCssSettings();
  }
  applyCssSettings() {
    if (this.styleTag) {
      this.styleTag.innerText = this.settings.customCss;
    }
  }
};
